language: cpp
dist: bionic

git:
  depth: 3

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install -y libboost-test-dev
  # line coverage only if gcc
  - "[ \"$TRAVIS_COMPILER\" = \"gcc\" ] && sudo apt-get install -y lcov || true"

before_script:
  - cd ${TRAVIS_BUILD_DIR} && cd build
  - cmake .. -DBUILD_TESTING=true -DCODE_COVERAGE=`[ "$TRAVIS_COMPILER" = "gcc" ] && echo true || echo false`
  - cmake --build .

script:
  - cd ${TRAVIS_BUILD_DIR} && cd build
  - ctest

after_script:
  - "
    [ \"$TRAVIS_COMPILER\" = \"gcc\" ] && 
    cd ${TRAVIS_BUILD_DIR} && 
    cd build && 
    make ccov-proc && 
    bash <(curl -s https://codecov.io/bash) -f coverage.info
    "
