language: cpp
dist: bionic

git:
  depth: 3

# branches:
  # only:
    # - master

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install -y libboost-test-dev
  # apt-get install -y lcov

before_script:
  - cd ${TRAVIS_BUILD_DIR} && cd build
  - cmake .. -DBUILD_TESTING=true -DCODE_COVERAGE=true
  - cmake --build .

script:
  - cd ${TRAVIS_BUILD_DIR} && cd build
  - ./test_sdr
  - ./fuzz_sdr 20

after_script:
  - env